language: java
os: linux
dist: bionic
addons:
  mariadb: '10.4'
git:
  depth: 1
  quiet: true

before_install:
  - sudo mysql -u root --password="" < ../Data-Collection/scripts/mariadb_settings.sql

jobs:
  include:
    - stage: Test
      name: "Test refactoringml - Data-Collection: Java"
      jdk: oraclejdk11
      install:
        - cd ../Data-Collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=refactoringml.*Test test

    - name: "Test Integration Toyproject - Data-Collection: Java"
      jdk: oraclejdk11
      install:
        - cd ../Data-Collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.toyprojects.*Test test

    - name: "Test Integration Realproject ApacheCommonsCli - Data-Collection: Java"
      jdk: oraclejdk11
      install:
        - cd ../Data-Collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.realprojects.ApacheCommonsCli*Test test

    - name: "Test Integration Realproject ApacheCommonsCSV - Data-Collection: Java"
      jdk: oraclejdk11
      install:
        - cd ../Data-Collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.realprojects.ApacheCommonsCSV*Test test

    - name: "Run Canary ReactiveLocationIntegrationTest - Data-Collection: Java"
      jdk: oraclejdk11
      install:
        - cd ../Data-Collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.canaryprojects.ReactiveLocationIntegrationTest test

    - name: "Run Canary TelegramServerIntegrationTest - Data-Collection: Java"
      jdk: oraclejdk11
      install:
        - cd ../Data-Collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.canaryprojects.TelegramServerIntegrationTest test